
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LLM_BASE_URL=https://chatapi.akash.network/api/v1/chat/completions
      - AKASH_API_KEY=sk-_lcxhYOEc_tyeNA8ZUaMTA
    volumes:
      - .:/app
    depends_on:
      - vector_store
      # - ollama
    entrypoint: ["sleep", "infinity"]

  vector_store:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_DB=llamaindex
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ollama:
  #   image: ollama/ollama
  #   ports:
  #     - "11434:11434"

volumes:
  pgdata:
